version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    target-branch: dev
    directory: /
    schedule:
      interval: daily
